services:
  logmap:
    container_name: logmap
    build:
      context: ./logmap
      dockerfile: logmap-dockerfile
    ports:
      - 22:22
    networks:
      - logmap-network
    # platform: linux/amd64

  rest-server:
    container_name: server
    build:
      context: ./rest-server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - logmap-network
    env_file:
      - ./rest-server/.env
    command: yarn start
    # volume for development only
    # mounts source code to container
    volumes:
      - ./rest-server:/usr/src/app

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - logmap-network
    environment:
      - REACT_APP_LOGMAP_API_URL=http://localhost:4000
    command: yarn start
    # volume for development only
    # mounts source code to container
    volumes:
      - ./web:/usr/src/app

networks:
  logmap-network:
    name: logmap-network
    driver: bridge
