services:
  doubler:
    build:
      context: ./doubler
      dockerfile: Dockerfile
    ports:
      - 22:22
    networks:
      - double-network

  rest-server:
    build:
      context: ./rest-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - double-network
    command: yarn start

networks:
  double-network:
    driver: bridge
